# Generated by Django 4.1.1 on 2022-09-13 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audioclips', '0002_audioclip_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclip',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='audioclip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
